# Generated by Django 6.0.2 on 2026-02-08 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ccse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcion',
            options={'verbose_name': 'Opción', 'verbose_name_plural': 'Opciones'},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['numero'], 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='es_correcta',
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='pregunta',
        ),
        migrations.AlterField(
            model_name='opcion',
            name='texto',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.TextField(unique=True),
        ),
        migrations.CreateModel(
            name='PreguntaOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='¿Es correcta para esta pregunta?')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de aparición')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcion_preguntas', to='app_ccse.opcion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_opciones', to='app_ccse.pregunta')),
            ],
            options={
                'verbose_name': 'Relación Pregunta-Opción',
                'verbose_name_plural': 'Relaciones Pregunta-Opción',
                'ordering': ['orden', 'id'],
                'unique_together': {('pregunta', 'opcion')},
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='opciones',
            field=models.ManyToManyField(related_name='preguntas', through='app_ccse.PreguntaOpcion', through_fields=('pregunta', 'opcion'), to='app_ccse.opcion'),
        ),
    ]
