# Generated by Django 6.0.2 on 2026-02-09 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ccse', '0002_alter_opcion_options_alter_pregunta_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, unique=True, verbose_name='Tipo de examen')),
            ],
            options={
                'verbose_name': 'Tipo de examen',
                'verbose_name_plural': 'Tipos de examen',
            },
        ),
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Calificación')),
                ('fecha_examen', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del examen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_examen', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('tipo_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='app_ccse.tipoexamen', verbose_name='Tipo de examen')),
            ],
            options={
                'verbose_name': 'Resultado de examen',
                'verbose_name_plural': 'Resultados de examen',
                'ordering': ['-fecha_examen'],
                'unique_together': {('user', 'tipo_examen', 'calificacion', 'fecha_examen')},
            },
        ),
    ]
